INSERT INTO muscle_groups (ID, Name, Category) VALUES
                                                 ('bk_1', 'Upper back muscle', 'back'),
                                                 ('bk_2', 'Shoulder blade muscle [RT]', 'back'),
                                                 ('bk_3', 'Shoulder blade muscle [LT]', 'back'),
                                                 ('bk_4', 'Lower shoulder muscle [RT]', 'back'),
                                                 ('bk_5', 'Lower shoulder muscle [LT]', 'back'),
                                                 ('bk_6', 'Side back muscle [RT]', 'back'),
                                                 ('bk_7', 'Side back muscle [LT]', 'back'),
                                                 ('bk_8', 'Shoulder muscle [RT]', 'back'),
                                                 ('bk_9', 'Shoulder muscle [LT]', 'back'),
                                                 ('bk_10', 'Back of upper arm [RT]', 'back'),
                                                 ('bk_11', 'Back of upper arm [LT]', 'back'),
                                                 ('bk_12', 'Outer wrist extender [RT]', 'back'),
                                                 ('bk_13', 'Outer wrist extender [LT]', 'back'),
                                                 ('bk_14', 'Inner wrist flexor [RT]', 'back'),
                                                 ('bk_15', 'Inner wrist flexor [LT]', 'back'),
                                                 ('bk_16', 'Upper butt muscle [RT]', 'back'),
                                                 ('bk_17', 'Upper butt muscle [LT]', 'back'),
                                                 ('bk_18', 'Main butt muscle [RT]', 'back'),
                                                 ('bk_19', 'Main butt muscle [LT]', 'back'),
                                                 ('bk_20', 'Outer thigh muscle [RT]', 'back'),
                                                 ('bk_21', 'Outer thigh muscle [LT]', 'back'),
                                                 ('bk_22', 'Hamstring muscle [RT]', 'back'),
                                                 ('bk_23', 'Hamstring muscle [LT]', 'back'),
                                                 ('bk_24', 'Middle hamstring [RT]', 'back'),
                                                 ('bk_25', 'Middle hamstring [LT]', 'back'),
                                                 ('bk_26', 'Inner hamstring [RT]', 'back'),
                                                 ('bk_27', 'Inner hamstring [LT]', 'back'),
                                                 ('bk_28', 'Inner thigh muscle [RT]', 'back'),
                                                 ('bk_29', 'Inner thigh muscle [LT]', 'back'),
                                                 ('bk_30', 'Calf muscle [RT]', 'back'),
                                                 ('bk_31', 'Calf muscle [LT]', 'back');

-- Front (Category: front)
INSERT INTO muscle_groups (ID, Name, Category) VALUES
                                                 ('ft_1', 'Neck muscle [RT]', 'front'),
                                                 ('ft_2', 'Neck muscle [LT]', 'front'),
                                                 ('ft_3', 'Upper back muscle [RT]', 'front'),
                                                 ('ft_4', 'Upper back muscle [LT]', 'front'),
                                                 ('ft_5', 'Shoulder muscle [RT]', 'front'),
                                                 ('ft_6', 'Shoulder muscle [LT]', 'front'),
                                                 ('ft_7', 'Chest muscle [RT]', 'front'),
                                                 ('ft_8', 'Chest muscle [LT]', 'front'),
                                                 ('ft_9', 'Abs', 'front'),
                                                 ('ft_10', 'Side rib muscle [RT]', 'front'),
                                                 ('ft_11', 'Side rib muscle [LT]', 'front'),
                                                 ('ft_12', 'Side abs [RT]', 'front'),
                                                 ('ft_13', 'Side abs [LT]', 'front'),
                                                 ('ft_14', 'Front of upper arm [RT]', 'front'),
                                                 ('ft_15', 'Front of upper arm [LT]', 'front'),
                                                 ('ft_16', 'Forearm muscle [RT]', 'front'),
                                                 ('ft_17', 'Forearm muscle [LT]', 'front'),
                                                 ('ft_18', 'Inner forearm flexor [RT]', 'front'),
                                                 ('ft_19', 'Inner forearm flexor [LT]', 'front'),
                                                 ('ft_20', 'Wrist muscle [RT]', 'front'),
                                                 ('ft_21', 'Wrist muscle [LT]', 'front'),
                                                 ('ft_22', 'Upper butt muscle [RT]', 'front'),
                                                 ('ft_23', 'Upper butt muscle [LT]', 'front'),
                                                 ('ft_24', 'Outer thigh muscle [RT]', 'front'),
                                                 ('ft_25', 'Outer thigh muscle [LT]', 'front'),
                                                 ('ft_26', 'Front thigh muscle [RT]', 'front'),
                                                 ('ft_27', 'Front thigh muscle [LT]', 'front'),
                                                 ('ft_28', 'Long inner thigh muscle [RT]', 'front'),
                                                 ('ft_29', 'Long inner thigh muscle [LT]', 'front'),
                                                 ('ft_30', 'Inner groin muscle [RT]', 'front'),
                                                 ('ft_31', 'Inner groin muscle [LT]', 'front'),
                                                 ('ft_32', 'Inner thigh muscle [RT]', 'front'),
                                                 ('ft_33', 'Inner thigh muscle [LT]', 'front'),
                                                 ('ft_34', 'Outer thigh muscle [RT]', 'front'),
                                                 ('ft_35', 'Outer thigh muscle [LT]', 'front'),
                                                 ('ft_36', 'Thin inner thigh muscle [RT]', 'front'),
                                                 ('ft_37', 'Thin inner thigh muscle [LT]', 'front'),
                                                 ('ft_38', 'Calf muscle [RT]', 'front'),
                                                 ('ft_39', 'Calf muscle [LT]', 'front'),
                                                 ('ft_40', 'Lower calf muscle [RT]', 'front'),
                                                 ('ft_41', 'Lower calf muscle [LT]', 'front'),
                                                 ('ft_42', 'Shin muscle [RT]', 'front'),
                                                 ('ft_43', 'Shin muscle [LT]', 'front'),
                                                 ('ft_44', 'Outer lower leg muscle [RT]', 'front'),
                                                 ('ft_45', 'Outer lower leg muscle [LT]', 'front');
